name: Doc

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Build HTML
      run: |
        python -m pip install -e .
        python -m pip install sphinx furo sphinx-copybutton
        cd doc
        make html
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: doc/_build/html/
  deploy-docs:
      runs-on: ubuntu-latest
      needs: build-docs
      if: startsWith(github.ref, 'refs/tags/v')
      permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 # or the latest "vX.X.X" version tag for this action
